export const Code = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  SERVER_NOT_ALLOWLISTED: 'SERVER_NOT_ALLOWLISTED',
  SERVER_REVOKED: 'SERVER_REVOKED',
  TOOL_NOT_ALLOWLISTED: 'TOOL_NOT_ALLOWLISTED',
  INPUT_SCHEMA_INVALID: 'INPUT_SCHEMA_INVALID',
  OUTPUT_SCHEMA_INVALID: 'OUTPUT_SCHEMA_INVALID',
  DOMAIN_NOT_ALLOWED: 'DOMAIN_NOT_ALLOWED',
  PATH_NOT_ALLOWED: 'PATH_NOT_ALLOWED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVAL_REPLAYED: 'APPROVAL_REPLAYED',
  APPROVAL_SCOPE_MISMATCH: 'APPROVAL_SCOPE_MISMATCH'
});
