export const Decision = Object.freeze({
  ALLOW: 'allow',
  DENY: 'deny'
});

export const ReasonCode = Object.freeze({
  ALLOWED: 'ALLOWED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_DENIED: 'RESOURCE_DENIED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVAL_SCOPE_MISMATCH: 'APPROVAL_SCOPE_MISMATCH',
  APPROVAL_REPLAYED: 'APPROVAL_REPLAYED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED'
});
